package com.smarttrader.learning;

public enum MistakeTaxonomy {
    LATE_ENTRY, EARLY_ENTRY, FALSE_BREAKOUT, TREND_MISREAD,
    REVERSAL_MISSED, POOR_RISK_REWARD, STOP_TOO_TIGHT, STOP_TOO_WIDE,
    TARGET_TOO_CLOSE, TARGET_TOO_FAR, OVERTRADING, LOW_LIQUIDITY,
    HIGH_SLIPPAGE, WRONG_MARKET_REGIME, SECTOR_WEAKNESS,
    CONFLICTING_INDICATORS, ML_FALSE_POSITIVE, ML_FALSE_NEGATIVE,
    AI_OVERCONFIDENCE, AI_UNDERCONFIDENCE, BAD_POSITION_SIZE,
    EXCESSIVE_EXPOSURE, DUPLICATE_SIGNAL, BAD_EXIT, MISSED_EXIT,
    UNEXPECTED_VOLATILITY
}
